package:
  name: seismic-python
  version: "0.0a0"

source:
  git_rev:
  git_url: https://github.com/malcolmw/seismic-python.git

requirements:
  build:
    - setuptools
  run:
    - basemap
    - matplotlib
    - numpy
    - obspy
    - pandas
    - scipy
test:
  imports:

about:
  home: https://github.com/malcolmw/seismic-python
  license: GPL
  license_file: LICENSE
